### ISSUE TITLE
Remove useless code in Interact listener

### ISSUE THREAD

**Issue by gumikacsa-dev** [Irantwomiles/Factions#1]
That switch block is just fucking my retina, instead you could make a multi-case switch block and do WordUtils.capitalizeFully(type.name().replace('_', ' ')); to get the type's name, it would already improve the look of it, ps. feel free to group listeners into one, for ex. the disconnect and login listeners into PlayerListeners

**Comment by sghofrany** [comment]
Ok I didn't know such thing existed @Vertises I'm gonna look and see how that works and try and replace it.

**Comment by sghofrany** [comment]
@Vertises So, I was looking and couldn't really find anything on multi-case switch block, do you mind giving me a link or something to point me in the right direction?

EDIT: I think I know what you are saying and I feel so fucking dumb. Idk why I've been doing that.

**Comment by gumikacsa-dev** [comment]
switch(meme):  {
case spicy:
case funny:
acceptMeme(meme);
default: rejectMeme(meme);
}
