### ISSUE TITLE
Couple of cool features

### ISSUE THREAD

**Issue by MuhammedKadic** [Irantwomiles/Factions#3]
Add clickable texts 
co-leaders
a cool settings page
database integration MONGO MYSQL or REDIS

**Comment by sghofrany** [comment]
Will take those into consideration @Kerbyy

**Comment by MuhammedKadic** [comment]
I can list much more if you need any ideas.

**Comment by sghofrany** [comment]
yea, just make a list of all of the ideas you'd like to see.
