### ISSUE TITLE
Enchanting Error

### ISSUE THREAD

**Issue by lukemango2** [Irantwomiles/Factions#5]
When rightclicking Enchantment Tables, I get this: https://pastebin.com/E1Kcqqv4

**Comment by lukemango2** [comment]
also happening with furnaces, chests
basically anything with a gui interface

**Comment by sghofrany** [comment]
Can you send me a screenshot of all of the config files

**Comment by sghofrany** [comment]
From the stacktrace it seems that you're running a 1.8.3 server. This plugin is made using a 1.7.10 paperspigot if I remember correctly. So try using that spigot instead, but if you have to use 1.8.3, make sure its a paperspigot.

**Comment by lukemango2** [comment]
We're using 1.8.8 Paper,
https://pastebin.com/u/lukemango/1/B9L4waND
All there

**Comment by sghofrany** [comment]
Can you send me a download link to your paperspigot

**Comment by lukemango2** [comment]
https://papermc.io/ci/job/Paper/443/

**Comment by sghofrany** [comment]
> https://papermc.io/ci/job/Paper/443/

I tested it with 1.7.10 and it worked just fine.

**Comment by lukemango2** [comment]
Does it not work with 1.8.8?

**Comment by sghofrany** [comment]
@lukemango I don't know. I haven't tested.
